TODO/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^manage/', include('managTask.urls')),
    url(r'^', include('homepage.urls')),
]

homepage/urls.py
from django.conf.urls import url
from . import views

app_name = 'homepage'


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/', views.login, name="login"),
    url(r'^signup/', views.signup, name="signup"),
    url(r'^signUpUser/', views.signUpUser, name="signUpUser"),
    url(r'^loginUser/', views.loginUser, name="loginUser"),
]

managTask/urls.py
from django.conf.urls import url
from . import views

app_name = 'manage'


urlpatterns = [
    # /manage/
    url(r'^$', views.index, name="index"),
    # /manage/userid
    url(r'^(?P<user_id>[0-9]+)/$', views.details_user, name='details_user'),
    # Add Task
    url(r'^addTask/', views.addTask, name='addTask'),
]

homepage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

managTask/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Users(models.Model):
    userid = models.CharField(max_length=50) #Auto Generated
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    username = models.CharField(max_length=50)

    def __str__(self):
        return self.username+" - "+self.password

class Task(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    task = models.CharField(max_length=255)
    date = models.CharField(max_length=10)
    status = models.CharField(max_length=10)

homepage/views.py
from django.http import Http404
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from managTask.models import Users
import string
import random
from datetime import datetime

# from django.template import loader
# Create your views here.

def index(request):
    # request.session['username'] = 'Sowmya'
    us = ''
    try:
        users = Users.objects.all()
        for user in users:
            if user.email == request.session['email']:
                us = user
                break
        if 'username' in request.session:
            x = request.session['username']
        else:
            x = ''
    except:
        return render(request, 'todo/index.html')
    return render(request, 'todo/index.html',{'user': us,'session_set':request.session['username']})

def login(request):
    # request.session['username'] = 'Sowmya'
    return render(request, 'todo/login.html', {})

def signup(request):
    return render(request, 'todo/signup.html', {})

def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def signUpUser(request):
    us = Users(userid=id_generator(), password=request.POST["password"], email=request.POST["email"], phone=request.POST["phone"], username=request.POST["username"])
    us.save()
    return render(request,'todo/index.html')

def loginUser(request):
    user = get_object_or_404(Users, email=request.POST['email'], password=request.POST['password'])
    request.session['username'] = user.username
    request.session['email'] = request.POST['email']
    request.session['id'] = user.id
    return render(request, 'todo/index.html', {'user': user,'session_set':request.session['username']})

managTask/views.py
from django.http import Http404
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from .models import Users, Task
# Create your views here.

def index(request):
    all_users = Users.objects.all()
    # template = loader.get_template('todo/index.html')
    # request.session['username'] = 'Sowmya'
    context = {'all_users' : all_users, 'session_set':request.session['username']}
    # html = ''
    # for user in all_users:
    #     url ='/manage/'+str(user.id)+'/'
    #     html += '<a href="'+url+'">'+user.username+'</a><br>'
    # return HttpResponse(template.render(context,request))
    return render(request, 'todo/index.html', context)

def details_user(request, user_id):
    # return HttpResponse("<h2>"+str(user_id)+"</h2>")
    # try:
    #     all_users = Users.objects.get(pk=user_id)
    # except Users.DoesNotExist:
    #     raise Http404('User not in database')
    all_users = get_object_or_404(Users, pk=user_id)
    return render(request,'todo/detailuser.html', {'user' : all_users} )

def addTask(request):
    userid = request.session['id']
    task = Task()
    user = Users.objects.get(pk=userid)
    task.user = user
    task.date = request.POST['date_task']
    task.status = request.POST['title_task']
    task.task = request.POST['details_task']
    task.save()
    return render(request, 'todo/index.html', {'user': user, 'session_set': request.session['username']})

managTask/templates/todo/detailuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User details</title>
</head>
<body>
Hi :- {{ user.username }}<br>
Your id is : {{ user.id }}<br>
Email: {{ user.email }}
<br><b>
Your Task's:</b>
<ol>
    {% for t in user.task_set.all %}
        <li>{{ t.task }} <b>{{ t.date }}</b></li>
    {% endfor %}
</ol>


</body>
</html>

managTask/templates/todo/headder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo ListManager</title>
    <!--<link rel="stylesheet" type="text/css" href="style.css">-->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage:index' %}">TODO Manager</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'homepage:index' %}">Home</a></li>
                {% if session_set %}
                <li><a  data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-plus"></span> Add Task</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Today task's <i class="fa fa-th-list" aria-hidden="true"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Page 1-1</a></li>
                        <li><a href="#">Page 1-2</a></li>
                        <li><a href="#">Page 1-3</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> Calender</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if session_set %}
                    <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i>
                    Welcome {% block username %}{% endblock %}</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
               {% else %}
                <li><a href="{% url 'homepage:signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Sign Up</a></li>
                <li><a href="{% url 'homepage:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
               {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}
 <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add New task</h4>
        </div>
          <form method="post" action="{% url 'manage:addTask' %}">
        <div class="modal-body">
                    {%  csrf_token %}
                    <input name="title_task" class="form-control" required placeholder="Enter Title fo task">
                    <textarea name="details_task" class="form-control" required placeholder="Enter task todo"></textarea>
                    <input name="date_task" class="form-control" type="date" required placeholder="Enter date of task">
        </div>
        <div class="modal-footer">
            <input class="btn btn-success" type="submit" value="+ Add Task">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
              </form>
      </div>
    </div>
  </div>
</body>
</html>

managTask/templates/todo/index.html
{% extends 'todo/headder.html' %}

{% block username %}
    {{ session_set }}
{% endblock %}

{% block body %}
<div class="container">
    <h2>Today Task's</h2>
    <div class="list-group">
        {% for t in user.task_set.all %}
            <div class="task">
            <div class="rt action_icons">
                <span class="cd glyphicon glyphicon-edit"></span>
                <span class="cd glyphicon glyphicon-remove"></span>
            </div>
                <div class="rt task_title">{{ t.status}}</div>
                <div class="rt task_body"><b>{{ t.date }}</b></div>
                <div class="rt task_body">{{ t.task }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
<!--<ul>-->
    <!--{% for user in all_users %}-->
    <!--<li><a href="/manage/{{ user.id }}/">{{ user.username }}</a></li>-->
    <!--<li><a href="{% url 'manage:details_user' user.id %}">{{ user.username }}</a></li>-->
    <!--{% endfor %}-->
<!--</ul>-->

managTask/templates/todo/login.html
{% extends 'todo/headder.html' %}
<style>
    .form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}
</style>
{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Sign in </h1>
            <div class="account-wall">
                <form class="form-signin" method="post" action="{% url 'homepage:loginUser' %}">
                     {% csrf_token %}
                <input type="email" class="form-control" name="email" placeholder="Email" required autofocus>
                <input type="password" class="form-control" name="password" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
                </form>
            </div>
            <a href="{% url 'homepage:signup' %}" class="text-center new-account">Create an account </a>
        </div>
    </div>
</div>
{% endblock %}

managTask/templates/todo/signup.html
{% extends 'todo/headder.html'%}
<style>
    .form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}
</style>
{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Signup</h1>
            <div class="account-wall">
                <form class="form-signin" method="post" action="{% url 'homepage:signUpUser' %}">
                    {% csrf_token %}
                    <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
                    <input type="Email" class="form-control" name="email" placeholder="Email" required>
                    <input type="text" class="form-control" name="phone" placeholder="Phone number" required>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
                    <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}